# Generated by Django 4.0.4 on 2022-06-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='account',
            new_name='account_number',
        ),
    ]
